import { StyleSheet } from "react-native";
import { colors, radius, shadow } from "./theme.js";

export const shared = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background, padding: 16 },
  title: { fontSize: 22, fontWeight: "800", color: colors.text, marginBottom: 12 },
  error: { color: colors.danger, backgroundColor: colors.dangerSoft, borderRadius: radius.sm, padding: 11, marginBottom: 10, fontWeight: "600" },
  success: { color: colors.primaryDark, backgroundColor: colors.primarySoft, borderRadius: radius.sm, padding: 11, marginBottom: 10, fontWeight: "600" },
  searchRow: { flexDirection: "row", gap: 10, marginBottom: 14 },
  searchInput: { flex: 1, minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: 15, paddingVertical: 11, backgroundColor: colors.surface, color: colors.text, fontSize: 15 },
  searchButton: { minHeight: 48, justifyContent: "center", paddingHorizontal: 18, borderRadius: radius.md, backgroundColor: colors.primary },
  searchButtonText: { color: colors.surface, fontWeight: "700" },
  fab: { position: "absolute", right: 20, bottom: 20, width: 58, height: 58, borderRadius: 29, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", ...shadow },
  fabText: { color: colors.surface, fontSize: 28, lineHeight: 30, fontWeight: "400" },
  card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: 15, marginBottom: 10, ...shadow },
  cardTitleRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  cardTitle: { fontSize: 15, fontWeight: "700", color: colors.text, flex: 1, paddingRight: 8 },
  cardMeta: { color: colors.textMuted, fontSize: 12, lineHeight: 18, marginTop: 4 },
  cardValue: { fontWeight: "800", color: colors.primary, fontSize: 15 },
  empty: { color: colors.textMuted, textAlign: "center", marginTop: 30, padding: 26, backgroundColor: colors.surface, borderWidth: 1, borderStyle: "dashed", borderColor: colors.border, borderRadius: radius.md },
  editButton: { minHeight: 38, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceMuted, borderRadius: radius.sm, paddingHorizontal: 14, paddingVertical: 8, marginTop: 10, alignSelf: "flex-start", justifyContent: "center" },
  editButtonText: { color: colors.text, fontWeight: "700", fontSize: 12 },

  modalOverlay: { flex: 1, backgroundColor: "rgba(14,31,22,0.55)", justifyContent: "flex-end" },
  modalCard: { backgroundColor: colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 20, paddingTop: 10, paddingBottom: 22, maxHeight: "90%" },
  modalHandle: { alignSelf: "center", width: 42, height: 5, borderRadius: radius.pill, backgroundColor: colors.border, marginBottom: 14 },
  modalHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 18 },
  modalCloseButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.surfaceMuted, alignItems: "center", justifyContent: "center" },
  modalCloseText: { color: colors.textMuted, fontSize: 16, fontWeight: "800" },
  modalTitle: { fontSize: 20, fontWeight: "800", color: colors.text, flex: 1 },
  field: { marginBottom: 14 },
  label: { color: colors.text, marginBottom: 7, fontWeight: "600", fontSize: 13 },
  input: { minHeight: 48, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: radius.md, paddingHorizontal: 15, paddingVertical: 11, fontSize: 15, color: colors.text },
  row: { flexDirection: "row", gap: 10 },
  rowField: { flex: 1, minWidth: 0 },
  formActions: { flexDirection: "row", justifyContent: "flex-end", gap: 10, marginTop: 10 },
  secondaryButton: { minHeight: 48, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: radius.md, paddingHorizontal: 18, paddingVertical: 12, justifyContent: "center" },
  secondaryButtonText: { color: colors.text, fontWeight: "700", textAlign: "center" },
  primaryButton: { minHeight: 48, backgroundColor: colors.primary, borderRadius: radius.md, paddingHorizontal: 20, paddingVertical: 12, justifyContent: "center" },
  primaryButtonText: { color: colors.surface, fontWeight: "800", textAlign: "center" },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 14 },
  chip: { minHeight: 38, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: radius.pill, paddingHorizontal: 14, paddingVertical: 8, justifyContent: "center" },
  chipActive: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
  chipText: { color: colors.text, fontSize: 13, fontWeight: "600" },
  listContent: { paddingBottom: 96 },

  warning: { marginTop: 32, padding: 18, textAlign: "center", color: colors.warning, backgroundColor: colors.warningSoft, borderRadius: radius.md, borderWidth: 1, borderColor: "#F0D48C", fontWeight: "600" },
  productCard: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: 15, marginBottom: 8 },
  productCardDisabled: { opacity: 0.45 },
  productName: { fontWeight: "700", color: colors.text, paddingRight: 10 },
  productMeta: { color: colors.textMuted, fontSize: 12, marginTop: 3 },
  productPrice: { fontWeight: "800", color: colors.primary, fontSize: 15 },
  cart: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, padding: 16, marginTop: 10, ...shadow },
  cartTitle: { fontSize: 16, fontWeight: "800", color: colors.text, marginBottom: 10 },
  cartEmpty: { color: colors.textMuted, textAlign: "center", paddingVertical: 22 },
  cartItem: { borderBottomWidth: 1, borderBottomColor: colors.border, paddingVertical: 11, gap: 8 },
  cartItemTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  cartItemName: { fontWeight: "700", color: colors.text, flex: 1 },
  removeText: { color: colors.danger, fontSize: 22, paddingHorizontal: 10 },
  cartItemBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  cartItemUnit: { color: colors.textMuted, fontSize: 12, flex: 1 },
  qtyInput: { minHeight: 40, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceMuted, borderRadius: radius.sm, width: 60, textAlign: "center", paddingVertical: 6, marginHorizontal: 8, color: colors.text },
  cartItemSubtotal: { fontWeight: "800", color: colors.text },
  alcoholToggle: { minHeight: 46, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: 12, marginTop: 12 },
  alcoholToggleActive: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
  alcoholToggleText: { color: colors.text, fontSize: 13, fontWeight: "600" },
  totalRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "baseline", marginTop: 14, paddingTop: 14, borderTopWidth: 1, borderTopColor: colors.border },
  totalLabel: { color: colors.textMuted, fontWeight: "600" },
  totalValue: { fontWeight: "900", fontSize: 24, color: colors.text },
  paymentMethods: { flexDirection: "row", gap: 8, marginTop: 14 },
  paymentMethod: { flex: 1, minHeight: 46, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingVertical: 11, alignItems: "center", justifyContent: "center" },
  paymentMethodActive: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
  paymentMethodText: { color: colors.textMuted, fontWeight: "700", fontSize: 12 },
  paymentMethodTextActive: { color: colors.primaryDark },
  changeText: { color: colors.primaryDark, fontWeight: "700", marginTop: 8, marginBottom: 10 },
  chargeButton: { minHeight: 54, backgroundColor: colors.primary, borderRadius: radius.md, paddingVertical: 15, alignItems: "center", justifyContent: "center", marginTop: 6 },
  chargeButtonDisabled: { opacity: 0.45 },
  chargeButtonText: { color: colors.surface, fontWeight: "800", fontSize: 16 },
});
